### ISSUE TITLE
A bug? Seemingly inconsistent `ConfIntT` output

### ISSUE THREAD

**Issue by iago-pssjd** [gitedric/trajeR#5]
Dear Cédric,

For what I see in slide 30 of https://orbilu.uni.lu/bitstream/10993/47791/2/2021_1%20CNRIUT.pdf, it seems like `ConfIntT` produces confidence intervals for the outputs of `propAssign`. Is this right? If it is, the example in the documentation produces weird results:
```r
data = read.csv(system.file("extdata", "CNORM2gr.csv", package = "trajeR"))
data = as.matrix(data)
sol = trajeR(Y = data[, 2:6], A = data[, 7:11], degre = c(2,2), Model = "CNORM", Method = "EM")
ConfIntT(sol, Y = data[, 2:6], A = data[, 7:11])
         [,1]         [,2]
1%  0.9951695 0.0008049469
99% 0.9991951 0.0048304654
propAssign(sol, Y = data[, 2:6], A = data[, 7:11])
        1    2
[1,] 0.38 0.62
```

How should I understand these outputs?

**Comment by gitedric** [comment]
I corrected the function ConfInt. Thus it must work.

**Comment by iago-pssjd** [comment]
Thanks!
